name: Add issue to project board
on:
  issues:
    types: [opened]
jobs:
  add-card:
    runs-on: ubuntu-latest
    steps:
        - uses: alex-page/github-project-automation-plus@v0.8.1
          with:
            project: GSA Development
            column: Triage
            repo-token: ${{ secrets.GITHUB_TOKEN }}