name: Add issue to project board
on:
  issues:
    types: [opened]
jobs:
  add-card:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Project Automation+
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: 'GSA Development'
          column: 'Open'
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}