name: Change labels according to project status
on:
  project_card:
    types:
      - moved
jobs:
  needs-more-info:
    if: github.event.project_card.column_id == '17839100'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: activate needs more info label
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: 'status: needs more info'
          remove-labels: "status: backlog, status: planned, status: in progress, status: ready for live, status: to be tested"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  backlog:
    if: github.event.project_card.column_id == '17839093'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: activate backlog label
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: 'status: backlog'
          remove-labels: "status: needs more info, status: planned, status: in progress, status: ready for live, status: to be tested"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  planned:
    if: github.event.project_card.column_id == '17839099'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: activate planned label
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: 'status: planned'
          remove-labels: "status: needs more info, status: backlog, status: in progress, status: ready for live, status: to be tested"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  in-progress:
    if: github.event.project_card.column_id == '17839104'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: activate in-progress label
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: 'status: in progress'
          remove-labels: "status: needs more info, status: backlog, status: planned, status: ready for live, status: to be tested"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  ready-for-live:
    if: github.event.project_card.column_id == '17839105'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: activate ready-for-live label
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: 'status: ready for live'
          remove-labels: "status: needs more info, status: backlog, status: planned, status: in progress, status: to be tested"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  to-be-tested:
    if: github.event.project_card.column_id == '17839106'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: activate to-be-tested label
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: 'status: to be tested'
          remove-labels: "status: needs more info, status: backlog, status: planned, status: in progress, status: ready for live"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  done:
    if: github.event.project_card.column_id == '17839107'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: activate to-be-tested label
        uses: andymckay/labeler@1.0.4
        with:
          remove-labels: "status: needs more info, status: backlog, status: planned, status: in progress, status: ready for live, status: to be tested"
          repo-token: ${{ secrets.GITHUB_TOKEN }}